[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "debugpy>=1.8.12",
    "fastapi>=0.115.7",
    "lancedb>=0.18.0",
    "pandas>=2.2.3",
    "python-dotenv>=1.0.1",
]
